### PR TITLE
Add basic Appveyor CI config

### PR DESCRIPTION
**Pull request by webknjaz**
Ref #81 
Ref https://ci.appveyor.com

### CODE REVIEW

**Comment by tarpas** [comment]
Thanks.. Maybe some stupid questions. Are the tests passing on appveyor-ci now? How do I find out before merging?

**Comment by tarpas** [comment]
@webknjaz so it seems to be failing with "ERROR: InvocationError: 'C:\\projects\\pytest-testmon\\.tox\\python\\Scripts\\py.test.EXE --tb=native test'" . Did it work for you?

**Comment by webknjaz** [comment]
Sorry, I didn't check, because I do not have windows machine. You may try enabling builds on AppVeyor and it would probably trigger PR build for this branch (I'm not sure).

Anyway, it won't block PRs from merging unless you configure this in repo settings explicitly, thus it's harmless.

If it's very important to you, I could try enabling builds for my fork.

**Comment by webknjaz** [comment]
Here's the error happening in the project I referred to: https://ci.appveyor.com/project/CherryPy/cheroot/build/166/job/nlioynp1ls4xf3em#L215

It basically fails to guess proper encoding of files contents.

**Comment by webknjaz** [comment]
Okay, I see you enabled it and it fails only under Python 2 @ test_easy: https://ci.appveyor.com/project/tarpas/pytest-testmon/build/4/job/faav29mb5518x0ul#L96

**Comment by tarpas** [comment]
With your cheroot project you must be hitting #14 , sorry.

**Comment by webknjaz** [comment]
@tarpas wow, thanks for pointing that out. How can I locate that file?

**Comment by tarpas** [comment]
@webknjaz the last commit in master shows how to locate the file (but might bring new bugs), the last commit in fix_utf_crash is a fix, but not finished yet

**Comment by webknjaz** [comment]
@tarpas I suggest you using [cchardet](https://pypi.python.org/pypi/cchardet/2.1.1) with fallback to [chardet](https://pypi.python.org/pypi/chardet)

**Comment by tarpas** [comment]
Why not rely on the coding: xyz string in the py file header? I think that's the correct way and an external library for that is unecessary. I think I'll releaes a new version with proper fix soon.

**Comment by webknjaz** [comment]
sure, I've just wanted to point out additional way

**Pull request merged**
