### PR TITLE
pytest_collection_modifyitems: do not ignore selected tests

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/tarpas/pytest-testmon/issues/101

TODO:

- [ ] test

### CODE REVIEW

**Comment by blueyed** [comment]
Does this make sense?

An alternative fix appears to be:

```diff
     def pytest_runtestloop(self, session):
-        ignored_deselected = self.collection_ignored.union(self.deselected)
+        selected = {x.nodeid for x in self.selected}
+        ignored_deselected = self.collection_ignored.union(
+            self.deselected
+        ).difference(selected)
```

But it appears to be better to fix collection_ignored instead.

Regarding:
```python
        session.config.hook.pytest_deselected(
            items=([self.FakeItemFromTestmon(session.config)] *
                   len(self.collection_ignored.union(self.deselected))))
```
Shouldn't that only use `self.deselected`?
("collected 75 items / 1220 deselected" reads a bit weird, i.e. there shouldn't be more deselected than collected ones)

**Comment by blueyed** [comment]
There is no test covering this case already.
I assume you have a better idea about how to trigger it?  (I've reproduced it using a copied/saved .testmondata file).

I guess it happens via `pytest_ignore_collect`, because all files touching the test(s) are unchanged?!

**Comment by blueyed** [comment]
@tarpas 
Please review - this certainly is an issue.
I would love to add some tests, but would also appreciate you doing it of course.. :)

**Comment by tarpas** [comment]
I understand the issue now, thanks for the PR. I'll get back to it today/day after.

**Comment by tarpas** [comment]
@blueyed I'm diving into this and I didn't find out if the original code has an error in the set operations or error in the assumptions about pytest_ignore_collect vs. pytest_collection_modifyitems.

Do you think it's possible an item from a file appears in pytest_collection_modifyitems even though that file has been flaged to ignore by pytest_ignore_collect?

**Comment by blueyed** [comment]
IIRC `pytest_ignore_collect` is called after `pytest_collection_modifyitems` - that's why this patch updates the list used therein.

**Comment by blueyed** [comment]
Oh, confused it with `pytest_runtestloop`, sorry.

**Comment by blueyed** [comment]
As per #101 I think the problem is that `pytest_ignore_collect` does not actually ignore it (the whole file), since it detects that it was changed (`self.collect_ignore`), but then the previous failed tests are still being reported as failed, although `test_should_run` says that it should run (and therefore the previous failure should not be reported).

**Comment by tarpas** [comment]
Thanks a lot Daniel, this has been helpful but I need to do a little refactoring along the way. This is equivalent https://github.com/tarpas/pytest-testmon/commit/3887a22d7b013e4fc858900f0d584f3a4504a8b7

**Pull request closed without merging**
